### ISSUE TITLE
#149 A user can edit a posted Quack

### ISSUE THREAD

**Issue by MelaninedUnicorn** [Neeham/Twitter-like-website#149]
As a user, I want to be able to edit a Quack that I have previously posted to the website.

**Comment by MelaninedUnicorn** [comment]
Sub-User story:
As a user, I should see when a Quack I am viewing has been edited.

**Comment by Amanda-Kolopa** [comment]
Issue is closed because the teacher and TA agreed that the team has met the additional feature requirement for Sprint 4.
