### ISSUE TITLE
#154 Clicking outside of Modal

### ISSUE THREAD

**Issue by Neeham** [Neeham/Twitter-like-website#154]
When clicking outside of the modal (alert box), the modal will close.

This should not happen as the URL will not be updated. Upon clicking on the x icon or close button, the modal closes and also updates the URL to remove the query which is displaying these alert box.

The clicking outside of the modal should be prevented. The user must click either the x icon or the close button when the modal displays in order to close it.

**Comment by Amanda-Kolopa** [comment]
Issue is resolved
