### ISSUE TITLE
#210 wrong label for "your feed"

### ISSUE THREAD

**Issue by zohalmir** [Neeham/Twitter-like-website#210]
<img width="1436" alt="Screen Shot 2019-03-27 at 5 09 36 PM" src="https://user-images.githubusercontent.com/43083525/55112533-2c0e1800-50b3-11e9-91e4-2cb390873561.png">

When on another user's profile, their list of quacks is under "your feed"!
change to Quacks..

**Comment by Neeham** [comment]
Problem has been resolved, good job Zohal! 😄
