### ISSUE TITLE
#22 A user can post a Quack

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Neeham/Twitter-like-website#22]
User Story:

As a client, I want to post messages to the Quack website so that the public can view it.

Risk Level: High
Priority Level: High
Story Points: 3

**Comment by Amanda-Kolopa** [comment]
Sub-User Story:

As a user, I should be able to post a message in a text box containing a maximum of 500 characters.

**Comment by Amanda-Kolopa** [comment]
Sub-User Story:

As a client, I should be able to post a message in a text box containing a maximum of 255 characters.

**Comment by zohalmir** [comment]
Sub-User Story:

As a client, I should be allowed to post my Quacks on my profile page.

**Comment by MelaninedUnicorn** [comment]
Sub-User Story:
As a client, I should be notified when my Quack has been posted to the website

**Comment by Neeham** [comment]
I believe it's time to close this issue as it has been resolved.

@zohalmir The client is able to post quack on their profile.
@MelaninedUnicorn  The client will be notified whether the quack has been posted or not (error occured).

@Amanda-Kolopa The client is able to post quack on their profile but the public cannot view it yet. This will be another issue where once you follow the user you can view their quack on your homepage.

This issue will now be closed if any feel like it should be opened again then feel free to do so 😄

**Comment by oussamus** [comment]
![image](https://user-images.githubusercontent.com/44511759/54041067-c7872980-4194-11e9-8f24-70f4ba0420e7.png)
