### ISSUE TITLE
#42 A user can like a tweet 

### ISSUE THREAD

**Issue by MelaninedUnicorn** [Neeham/Twitter-like-website#42]
User Story:
As a client, I want the ability to react to a message on the Quack website by liking it.

**Comment by MelaninedUnicorn** [comment]
Sub User-Story:
As a client, I want to unlike a message I previously liked.
As a client, I want to view all the messages I have liked.

**Comment by MelaninedUnicorn** [comment]
Sub User-Story:
As a client, I want to unlike a message I previously liked.

**Comment by Neeham** [comment]
I am going to close this issue since it is officially working. If ever there is the need to reopen this issue, we will do so.

**Comment by oussamus** [comment]
![image](https://user-images.githubusercontent.com/44511759/53895071-3a5e9c00-3fff-11e9-8258-72a9e56414a8.png)
