### ISSUE TITLE
#43 A user can follow another user 

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Neeham/Twitter-like-website#43]
As a client, I want the ability to read posted messages from a list of specified user accounts.

**Comment by Amanda-Kolopa** [comment]
Sub-user story:

As a client, I want to view the messages on the home page of the Quack website.

**Comment by Loujain-Al-Nakeeb** [comment]
Sub-user story:

As a client, I should be able to follow another user by visiting their profile page.

**Comment by Neeham** [comment]
This feature has officially been implemented. Closing this issue now.

**Comment by oussamus** [comment]
![image](https://user-images.githubusercontent.com/44511759/53895184-72fe7580-3fff-11e9-9f14-e3e3c555944c.png)
