### ISSUE TITLE
#48 A new user can create an account

### ISSUE THREAD

**Issue by oussamus** [Neeham/Twitter-like-website#48]
As a new client, I want to be able to create a new Quack account so that I can use all the website's features under my account.

**Comment by Amanda-Kolopa** [comment]
Sub-user story:

As a new client, I want to create a new Quack account by providing my full name, a username, password, and email address to the website.

**Comment by oussamus** [comment]
As a user, I want the website to notify me if the name, the username or the email is already associated with an existing account to avoid conflicts.

**Comment by Amanda-Kolopa** [comment]
Sub-user story:

As a new client, I should be notified when my account has been accepted by the website.
