### ISSUE TITLE
#22 Sub-user story: A user can post a tweet

### ISSUE THREAD

**Issue by Amanda-Kolopa** [Neeham/Twitter-like-website#49]
#22 Sub-User Story:

As a user, I am able to post a message in a text box containing a maximum of 255 characters.

**Comment by oussamus** [comment]
![image](https://user-images.githubusercontent.com/44511759/53894251-c8d21e00-3ffd-11e9-8db0-b5953138e622.png)

**Comment by oussamus** [comment]
![image](https://user-images.githubusercontent.com/44511759/53894797-befcea80-3ffe-11e9-92e5-94c423559c14.png)
