### ISSUE TITLE
#82 A user can delete a posted Quack

### ISSUE THREAD

**Issue by MelaninedUnicorn** [Neeham/Twitter-like-website#82]
As a user, I want to be able to delete a Quack that I have previously posted to the website.

**Comment by MelaninedUnicorn** [comment]
Sub-User story:
As a client, I should be notified when my Quack has been deleted from the website.

**Comment by Amanda-Kolopa** [comment]
Issue is closed because the teacher and TA agreed that the team has met the additional feature requirement for Sprint 4.
