### ISSUE TITLE
#83 A user can view the other users that they chose to follow

### ISSUE THREAD

**Issue by MelaninedUnicorn** [Neeham/Twitter-like-website#83]
As a user, I want to be able to view the list of users that I am currently following.

**Comment by MelaninedUnicorn** [comment]
Sub-User Story:
As a client, I should be able to view the total number of users that I am following.

**Comment by Neeham** [comment]
This feature has been implemented. There may be more tweaking to be done to better visualize it. For now this issue will be closed.
